//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoRaWAN.Utilities.Email.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilities.Email.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppealMessage.
        /// </summary>
        internal static string AppealMessage {
            get {
                return ResourceManager.GetString("AppealMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppealSubject.
        /// </summary>
        internal static string AppealSubject {
            get {
                return ResourceManager.GetString("AppealSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyAppealCancelMessage.
        /// </summary>
        internal static string CompanyAppealCancelMessage {
            get {
                return ResourceManager.GetString("CompanyAppealCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyAppealMessage.
        /// </summary>
        internal static string CompanyAppealMessage {
            get {
                return ResourceManager.GetString("CompanyAppealMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyAppealWaitingMessage.
        /// </summary>
        internal static string CompanyAppealWaitingMessage {
            get {
                return ResourceManager.GetString("CompanyAppealWaitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FleetAppealConfirmMessage.
        /// </summary>
        internal static string FleetAppealConfirmMessage {
            get {
                return ResourceManager.GetString("FleetAppealConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FleetAppealConfirmSubject.
        /// </summary>
        internal static string FleetAppealConfirmSubject {
            get {
                return ResourceManager.GetString("FleetAppealConfirmSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FleetAppealRejectMessage.
        /// </summary>
        internal static string FleetAppealRejectMessage {
            get {
                return ResourceManager.GetString("FleetAppealRejectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FleetAppealSubject.
        /// </summary>
        internal static string FleetAppealSubject {
            get {
                return ResourceManager.GetString("FleetAppealSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FleetUserCreateMessage.
        /// </summary>
        internal static string FleetUserCreateMessage {
            get {
                return ResourceManager.GetString("FleetUserCreateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FleetUserCreateSubject.
        /// </summary>
        internal static string FleetUserCreateSubject {
            get {
                return ResourceManager.GetString("FleetUserCreateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgotPasswordMessage.
        /// </summary>
        internal static string ForgotPasswordMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgotPasswordSubject.
        /// </summary>
        internal static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GasStationAppealConfirmMessage.
        /// </summary>
        internal static string GasStationAppealConfirmMessage {
            get {
                return ResourceManager.GetString("GasStationAppealConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GasStationAppealConfirmSubject.
        /// </summary>
        internal static string GasStationAppealConfirmSubject {
            get {
                return ResourceManager.GetString("GasStationAppealConfirmSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GasStationAppealRejectMessage.
        /// </summary>
        internal static string GasStationAppealRejectMessage {
            get {
                return ResourceManager.GetString("GasStationAppealRejectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GasStationAppealSubject.
        /// </summary>
        internal static string GasStationAppealSubject {
            get {
                return ResourceManager.GetString("GasStationAppealSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GasStationUserCreateMessage.
        /// </summary>
        internal static string GasStationUserCreateMessage {
            get {
                return ResourceManager.GetString("GasStationUserCreateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GasStationUserCreateSubject.
        /// </summary>
        internal static string GasStationUserCreateSubject {
            get {
                return ResourceManager.GetString("GasStationUserCreateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPasswordMessage.
        /// </summary>
        internal static string NewPasswordMessage {
            get {
                return ResourceManager.GetString("NewPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPasswordSubject.
        /// </summary>
        internal static string NewPasswordSubject {
            get {
                return ResourceManager.GetString("NewPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PosMachineAppealCancelMessage.
        /// </summary>
        internal static string PosMachineAppealCancelMessage {
            get {
                return ResourceManager.GetString("PosMachineAppealCancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PosMachineAppealConfirmMessage.
        /// </summary>
        internal static string PosMachineAppealConfirmMessage {
            get {
                return ResourceManager.GetString("PosMachineAppealConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PosMachineAppealConfirmSubject.
        /// </summary>
        internal static string PosMachineAppealConfirmSubject {
            get {
                return ResourceManager.GetString("PosMachineAppealConfirmSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PosMachineAppealRejectMessage.
        /// </summary>
        internal static string PosMachineAppealRejectMessage {
            get {
                return ResourceManager.GetString("PosMachineAppealRejectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PosMachineAppealSubject.
        /// </summary>
        internal static string PosMachineAppealSubject {
            get {
                return ResourceManager.GetString("PosMachineAppealSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PosMachineAppealWaitingMessage.
        /// </summary>
        internal static string PosMachineAppealWaitingMessage {
            get {
                return ResourceManager.GetString("PosMachineAppealWaitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCreateMessage.
        /// </summary>
        internal static string UserCreateMessage {
            get {
                return ResourceManager.GetString("UserCreateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCreateSubject.
        /// </summary>
        internal static string UserCreateSubject {
            get {
                return ResourceManager.GetString("UserCreateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebForgotPasswordMessage.
        /// </summary>
        internal static string WebForgotPasswordMessage {
            get {
                return ResourceManager.GetString("WebForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebForgotPasswordSubject.
        /// </summary>
        internal static string WebForgotPasswordSubject {
            get {
                return ResourceManager.GetString("WebForgotPasswordSubject", resourceCulture);
            }
        }
    }
}
